import { Project, ProjectType } from './index.d';

export const projects: Project[] = [
  {
    name: 'Google Translate Bot',
    description: 'Google Translate on Telegram Bot',
    type: ProjectType.BOT,
    tags: ['TypeScript', 'Node.js', 'Telegraf'],
    picture: 'translate-banner.jpg',
    repoLink: 'https://github.com/tfkhdyt/translate-bot',
  },
  {
    name: 'Portfolio Website',
    description: "You're here",
    type: ProjectType.WEB,
    tags: ['TypeScript', 'Next.js', 'Tailwind CSS'],
    picture: 'web-portfolio.jpg',
    repoLink: 'https://github.com/tfkhdyt/web-portfolio',
  },
  {
    name: 'Gatotkaca',
    description: 'Metaseach-engine, based on SearXNG',
    type: ProjectType.WEB,
    tags: ['Python', 'SearXNG'],
    picture: 'gatotkaca.png',
    repoLink: 'https://github.com/tfkhdyt/gatotkaca',
  },
  {
    name: 'Random Quote Generator',
    description: 'A web app that will generate a random quote for you',
    type: ProjectType.WEB,
    tags: ['TypeScript', 'Next.js', 'Tailwind CSS'],
    picture: 'quotes.png',
    repoLink: 'https://github.com/tfkhdyt/random-quote-generator',
  },
  {
    name: 'Full Stack Roadmap',
    description: 'Roadmap to become a Full Stack Developer',
    type: ProjectType.WEB,
    tags: ['TypeScript', 'Next.js', 'NestJS'],
    picture: 'full-stack-roadmap.png',
    repoLink: 'https://github.com/tfkhdyt/full-stack-roadmap',
  },
  {
    name: 'LAM Final Project',
    description: 'Web app to solve some linear algebra and matrices problems',
    type: ProjectType.WEB,
    tags: ['JavaScript', 'Next.js', 'Tailwind CSS'],
    picture: 'aljabarlinear.jpg',
    repoLink: 'https://github.com/tfkhdyt/tugas-akhir-aljabar-linier-matriks',
  },
  {
    name: 'KBBI Bot',
    description: 'Indonesian Dictionary in Telegram using web scraping method',
    type: ProjectType.BOT,
    tags: ['TypeScript', 'Cheerio', 'Telegraf'],
    picture: 'kbbi.jpg',
    repoLink: 'https://github.com/tfkhdyt/kbbi-bot',
  },
  {
    name: 'Movie Bot',
    description: 'Telegram Bot to search movies information',
    type: ProjectType.BOT,
    tags: ['Node.js', 'JavaScript', 'Telegraf'],
    picture: 'movie-bot.jpg',
    repoLink: 'https://github.com/tfkhdyt/tfkhdyt-movie-bot',
  },
  {
    name: 'Bayarcoek',
    description: 'Automation script to encrypt all files inside a folder',
    type: ProjectType.CLI,
    tags: ['Node.js', 'JavaScript', 'Commander.js'],
    picture: 'bayarcoek.jpg',
    repoLink: 'https://github.com/tfkhdyt/bayarcoek',
  },
  {
    name: '21 Cineplex API',
    description: 'REST API that scrape the data from 21Cineplex website',
    type: ProjectType.API,
    tags: ['TypeScript', 'NestJS', 'Cheerio'],
    picture: '21cineplex-api.jpg',
    repoLink: 'https://github.com/tfkhdyt/21cineplex-api',
  },
  {
    name: 'Form to Telegram API',
    description:
      'REST API to send message from HTML form into Telegram Messages',
    type: ProjectType.API,
    tags: ['NestJS', 'TypeScript', 'Telegraf'],
    picture: 'message_form_to_telegram_api.jpg',
    repoLink: 'https://github.com/tfkhdyt/message-form-to-telegram-api',
  },
  {
    name: 'Coursework',
    description: 'All of my college coursework',
    type: ProjectType.MISC,
    tags: ['Java', 'C++', 'Pascal'],
    picture: 'tugas-kuliah.jpg',
    repoLink: 'https://github.com/tfkhdyt/tugas-kuliah',
  },
  {
    name: 'Anime Naon Ieu?',
    description: 'Telegram Bot to find anime details from a screenshot',
    type: ProjectType.BOT,
    tags: ['Node.js', 'JavaScript', 'Telegraf'],
    picture: 'anibot.jpg',
    repoLink: 'https://github.com/tfkhdyt/anime-naon-ieu',
  },
  {
    name: 'MovieDB',
    description: 'Web app to search movie information',
    type: ProjectType.WEB,
    tags: ['JavaScript', 'Bootstrap'],
    picture: 'imdb.jpg',
    repoLink: 'https://github.com/tfkhdyt/imdb',
  },
  {
    name: '30 Hari Jago JavaScript',
    description: 'Web app to learn JavaScript in 30 days',
    type: ProjectType.WEB,
    tags: ['JavaScript', 'Bootstrap'],
    picture: '30days.jpg',
    repoLink: 'https://github.com/tfkhdyt/30DaysJagoJavaScript',
  },
  {
    name: 'School Website',
    description: 'SMKN 7 Baleendah school website with dynamic data',
    type: ProjectType.WEB,
    tags: ['PHP', 'Bootstrap'],
    picture: 'web-sekolah.jpg',
    repoLink: 'https://github.com/tfkhdyt/web-sekolah',
  },
  {
    name: 'Old Portfolio Website',
    description: 'My old portfolio website',
    type: ProjectType.WEB,
    tags: ['JavaScript', 'Bootstrap'],
    picture: 'old-web-portfolio.jpeg',
    repoLink: 'https://github.com/tfkhdyt/tfkhdyt-portfolio',
  },
  {
    name: 'YouTube DL Bot',
    description: 'Telegram Bot to download youtube videos',
    type: ProjectType.BOT,
    tags: ['Node.js', 'JavaScript', 'Telegraf'],
    picture: 'ytdl-bot-thumb.jpg',
    repoLink: 'https://github.com/tfkhdyt/youtube-dl-bot',
  },
  {
    name: 'POPOWI',
    description: 'Popcat.click clone with Jokowi as the character',
    type: ProjectType.WEB,
    tags: ['JavaScript', 'React', 'Bootstrap'],
    picture: 'popowi.jpg',
    repoLink: 'https://github.com/tfkhdyt/popclick',
  },
  {
    name: 'Donation Page',
    description: 'Simple Donation Page',
    type: ProjectType.WEB,
    tags: ['JavaScript', 'Bootstrap'],
    picture: 'donation-page.jpg',
    repoLink: 'https://github.com/tfkhdyt/donation-page',
  },
  {
    name: 'CRUD Express',
    description: 'Simple CRUD with Authentication',
    type: ProjectType.WEB,
    tags: ['Node.js', 'Express', 'Bootstrap'],
    picture: 'banner crud express.jpg',
    repoLink: 'https://github.com/tfkhdyt/data-tanaman-express',
  },
  {
    name: 'YouTube DL',
    description: 'A script to download videos from YouTube',
    type: ProjectType.CLI,
    tags: ['Bash', 'youtube-dlp'],
    picture: 'ytdl.jpg',
    repoLink: 'https://github.com/tfkhdyt/youtube-dl',
  },
  {
    name: 'Instant Video Compressor',
    description: 'Program to compress video but still maintain the quality',
    type: ProjectType.CLI,
    tags: ['Python', 'FFMPEG'],
    picture: 'ivc.png',
    repoLink: 'https://github.com/tfkhdyt/ivc',
  },
  {
    name: 'Degenerator Bot',
    description: 'Bot to generate degenerated copypasta',
    type: ProjectType.BOT,
    tags: ['Python', 'Flask', 'pyTelegramBotAPI'],
    picture: 'degenerator.jpg',
    repoLink: 'https://github.com/tfkhdyt/MyCopyPastaBot-src',
  },
  {
    name: 'CRUD Python',
    description: 'Simple CRUD with Python and SQLite',
    type: ProjectType.CLI,
    tags: ['Python', 'SQLite'],
    picture: 'crud-py.jpg',
    repoLink: 'https://github.com/tfkhdyt/crud-python',
  },
  {
    name: 'SpotifyDL',
    description: 'User friendly spotify-dl wrapper',
    type: ProjectType.CLI,
    tags: ['Bash', 'spotify-dl'],
    picture: 'spotify-dl.jpg',
    repoLink: 'https://github.com/tfkhdyt/SpotifyDL',
  },
];
