import { ISkills } from '.';

export const skills: ISkills[] = [
  {
    title: 'HTML',
    icon: 'html.svg',
    type: 'Language',
    isMainSkill: true,
  },
  {
    title: 'CSS',
    icon: 'css.svg',
    type: 'Language',
    isMainSkill: true,
  },
  {
    title: 'JavaScript',
    icon: 'js.svg',
    type: 'Language',
    isMainSkill: true,
  },
  {
    title: 'TypeScript',
    icon: 'ts.svg',
    type: 'Language',
    isMainSkill: true,
  },
  {
    title: 'Golang',
    icon: 'golang.svg',
    type: 'Language',
    isMainSkill: true,
  },
  {
    title: 'React (Library)',
    icon: 'react.svg',
    type: 'Framework/Library',
    isMainSkill: true,
  },
  {
    title: 'Next.js',
    icon: 'next.svg',
    type: 'Framework/Library',
    isMainSkill: true,
  },
  {
    title: 'Bootstrap',
    icon: 'bootstrap.svg',
    type: 'UI Framework/Component',
    isMainSkill: true,
  },
  {
    title: 'Tailwind CSS',
    icon: 'tailwind.svg',
    type: 'UI Framework/Component',
    isMainSkill: true,
  },
  {
    title: 'daisyUI (Component)',
    icon: 'daisy.svg',
    type: 'UI Framework/Component',
    isMainSkill: true,
  },
  {
    title: 'Mantine (Component)',
    icon: 'mantine.svg',
    type: 'UI Framework/Component',
    isMainSkill: true,
  },
  {
    title: 'Node.js (Runtime)',
    icon: 'node.svg',
    type: 'Framework/Library',
    isMainSkill: true,
  },
  {
    title: 'Java',
    icon: 'java.svg',
    type: 'Language',
  },
  {
    title: 'Python',
    icon: 'python.svg',
    type: 'Language',
  },
  {
    title: 'C++',
    icon: 'cpp.svg',
    type: 'Language',
  },
  {
    title: 'Rust',
    icon: 'rust.svg',
    type: 'Language',
  },
  {
    title: 'PHP',
    icon: 'php.svg',
    type: 'Language',
  },
  {
    title: 'Pascal',
    icon: 'pascal.png',
    type: 'Language',
  },
  {
    title: 'EJS',
    icon: 'ejs.svg',
    type: 'Language',
  },

  {
    title: 'Express',
    icon: 'express.svg',
    type: 'Framework/Library',
    isMainSkill: true,
  },
  {
    title: 'NestJS',
    icon: 'nest.svg',
    type: 'Framework/Library',
    isMainSkill: true,
  },
  {
    title: 'Gin',
    icon: 'gin.svg',
    type: 'Framework/Library',
    isMainSkill: true,
  },
  {
    title: 'Telegraf',
    icon: 'telegraf.svg',
    type: 'Framework/Library',
    isMainSkill: true,
  },
  {
    title: 'MongoDB',
    icon: 'mongo.svg',
    type: 'DBMS',
    isMainSkill: true,
  },
  {
    title: 'MySQL',
    icon: 'mysql.svg',
    type: 'DBMS',
    isMainSkill: true,
  },
  {
    title: 'PostgreSQL',
    icon: 'postgres.svg',
    type: 'DBMS',
    isMainSkill: true,
  },
  {
    title: 'SQLite',
    icon: 'sqlite.svg',
    type: 'DBMS',
  },
  {
    title: 'Zustand (Library)',
    icon: 'zustand.png',
    type: 'Framework/Library',
    isMainSkill: true,
  },
  {
    title: 'React Hook Form (Library)',
    icon: 'react-hook-form.svg',
    type: 'Framework/Library',
    isMainSkill: true,
  },
  {
    title: 'Redux Toolkit (Library)',
    icon: 'redux.svg',
    type: 'Framework/Library',
  },
  {
    title: 'Socket.io (Library)',
    icon: 'socketio.svg',
    type: 'Framework/Library',
  },
  {
    title: 'jQuery (Library)',
    icon: 'jquery.svg',
    type: 'Framework/Library',
  },
  {
    title: 'EndeavourOS (Distro)',
    icon: 'endeavouros.svg',
    type: 'Operating System',
    isMainSkill: true,
  },
  {
    title: 'Arch Linux (Distro)',
    icon: 'arch.svg',
    type: 'Operating System',
    isMainSkill: true,
  },
  {
    title: 'GNU/Linux',
    icon: 'linux.png',
    type: 'Operating System',
    isMainSkill: true,
  },
  {
    title: 'Android',
    icon: 'android.svg',
    type: 'Operating System',
    isMainSkill: true,
  },
  {
    title: 'Manjaro (Distro)',
    icon: 'manjaro.svg',
    type: 'Operating System',
  },
  {
    title: 'Windows 10',
    icon: 'win10.svg',
    type: 'Operating System',
  },
  {
    title: 'Windows 7',
    icon: 'win7.png',
    type: 'Operating System',
  },
  {
    title: 'Windows XP',
    icon: 'winxp.png',
    type: 'Operating System',
  },
];
