import Navbar from '@/components/Navbar';
import './globals.css';
import { Rubik } from 'next/font/google';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata = {
  title: 'Taufik Hidayat - Junior Back-end Developer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' id='html'>
      <body
        className={rubik.className
          + 'transition duration-300 bg-gruvbox-light-bg-primary dark:bg-gruvbox-dark-bg-primary'}
      >
        <>
          <Navbar />
          {children}
        </>
      </body>
    </html>
  );
}
